development:
  adapter: postgresql
  reconnect: false
  database: mutitennat_app_development_db
  username: postgres3
  password: postgres
  # socket: /Applications/MAMP/tmp/mysql/mysql.sock
test:
  adapter: postgresql
  reconnect: false
  database: mutitennat_app_development_db_test
  pool: 1024
  username: postgres3
  password: postgres
production:
  adapter: postgresql
  reconnect: false
  # database: mutitennat_app_db
  pool: 1024
  # username: root
  # password: zaqxsw
